# services:
#   mongodb:
#     image: mongo:7.0
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
#       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
#     volumes:
#       - ./mongo_data:/data/db
#     ports:
#       - 27017:27017

services:
  mongo:
    image: mongo:7.0 
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017